base_url = "https://zolartheme.netlify.app"
title = "Zolar"
description = "This is a solar-powered website, which means it sometimes goes offline"

default_language = "en"
generate_feed = true
compile_sass = true

# Built in taxonomies of zolar
taxonomies = [
           {name = "tags"},
           {name = "categories"},
]

[extra]
# Put all your custom variables here
#
# ---------------------------------------------------------

# Enable/disable functions relative to solar monitoring
solar = true

# Preferred time format
timeformat = "%B %Y"
timezone = "UTC"

# Custom css to style over the defaults. This is useful when you only have a
# few small tweaks to make rather than a major rehaul to the theme.
# It would be best to make this a proper .sass or .scss file in sass/ rather
# than placing in static/
# custom_css = "custom.css"

# Main menu links
main_menu = [
    { url="/about/", name="About" },
    { url="/categories/low-tech-solutions/", name="Low-tech Solutions", is_category=true },
    { url="/categories/high-tech-problems/", name="High Tech Problems", is_category=true },
    { url="/categories/obsolete-technology/", name="Obsolete Technology", is_category=true },
    { url="/offline-reading/", name="Offline Reading" },
    { url="/archives/", name="Archive" },
    { url="/donate/", name="Donate" },
]

# Bind categories to special colors and descriptions for links and related images
# If not specifically requested, you shouldn't expect any color other than black
special_categories = [ { name = "high-tech-problems", color = "#d11305", description = """
        High-tech has become the idol of our society, but technological progress is&mdash;
        more often than not&mdash;aimed at solving problems caused by earlier technical inventions.
        """ },

    { name = "low-tech-solutions", color = "#162dab", description = """
        Interesting possibilities arise when you combine old technology with new
        knowledge and new materials, or when you apply old concepts and traditional
        knowledge to modern technology.
        """ },

    { name = "obsolete-technology", color = "#006951", description = """
        There is a lot of potential in past and often forgotten knowledge and
        technologies when it comes to designing a sustainable society.
        """ },
]

email = "solar@lowtechmagazine.com"

social_links = [
    {url = "https://twitter.com/lowtechmagazine", name = "twitter"},
    {url = "https://www.facebook.com/Lowtechmagazine/", name = "facebook"},
    # {url = "https://github.com/gicrisf", name = "github"},
]

[extra.footer]
author = "Kris De Decker"
email = "solar [at] lowtechmagazine [dot] com"

info_menu = [
    {url = "/about/", name = "About the site"},
    {url = "/power/", name = "Power"},
    {url = "/colophon/", name = "Colophon"},
    {url = "/donate/", name = "Donate"},
    {url = "/privacy/", name = "Privacy Policy"},
]
